from app import app

@app.route('/')
def hello_world():
    return "Testing the pipeline"

# This ensures URLs generated by Flask-Freeze will have the right path
@app.route('/index.html')
def index_html():
    return hello_world()

