name: Docker CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install pipenv
      run: |
        pip install pipenv

    - name: Generate requirements.txt from Pipfile.lock
      run: |
        pipenv requirements > requirements.txt

    - name: Build Docker Image
      run: docker build -t my_flask_app .

    - name: Run Docker Container
      run: docker run -d --name flask_container my_flask_app

    - name: Freeze the app
      run: docker exec flask_container python freeze.py

    - name: List directories inside the container
      run: docker exec flask_container ls /app

    - name: Copy static files out of container
      run: docker cp flask_container:/app/app/build ./build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        BRANCH: gh-pages
        FOLDER: build
